###############################################################
#  Generated by:      Cadence Encounter 13.10-p003_1
#  OS:                Linux i686(Host ID cadence)
#  Generated on:      Fri Sep  4 02:36:13 2026
#  Design:            adas_accelerator_top
#  Command:           createClockTreeSpec -output clk.spec
###############################################################
#
# Encounter(R) Clock Synthesis Technology File Format
#

#-- MacroModel --
#MacroModel pin <pin> <maxRiseDelay> <minRiseDelay> <maxFallDelay> <minFallDelay> <inputCap>


#-- Special Route Type --
#RouteTypeName specialRoute
#TopPreferredLayer 4
#BottomPreferredLayer 3
#PreferredExtraSpace 1
#End

#-- Regular Route Type --
#RouteTypeName regularRoute
#TopPreferredLayer 4
#BottomPreferredLayer 3
#PreferredExtraSpace 1
#End

#-- Clock Group --
#ClkGroup
#+ <clockName>


#------------------------------------------------------------
# Clock Root   : clk
# Clock Name   : clk
# Clock Period : 20ns
# Clock Name   : clk
# Clock Period : 20ns
#------------------------------------------------------------
AutoCTSRootPin clk
Period         20ns
MaxDelay       0.01ns # sdc driven default
MinDelay       0ns # sdc driven default
MaxSkew        800ps # sdc driven default
SinkMaxTran    200ps # sdc driven default
BufMaxTran     200ps # sdc driven default
Buffer         CLKBUFX20 INVX20 CLKINVX20
NoGating       NO
DetailReport   YES
#SetDPinAsSync  NO
#SetIoPinAsSync NO
#SetASyncSRPinAsSync  NO
#SetTriStEnPinAsSync NO
#SetBBoxPinAsSync NO
RouteClkNet    YES
PostOpt        YES
OptAddBuffer   YES
#RouteType      specialRoute
#LeafRouteType  regularRoute
END

